"""Init

Revision ID: e5d943af33bc
Revises: 
Create Date: 2018-06-16 23:10:46.033083

"""
from alembic import op
import sqlalchemy as sa

from app.models import GroupType

# revision identifiers, used by Alembic.
revision = 'e5d943af33bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_name', sa.String(length=32), nullable=False),
    sa.Column('beaten_name', sa.String(length=32), nullable=False),
    sa.Column('killed', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fights_beaten_name'), 'fights', ['beaten_name'], unique=False)
    op.create_index(op.f('ix_fights_killed'), 'fights', ['killed'], unique=False)
    op.create_index(op.f('ix_fights_winner_name'), 'fights', ['winner_name'], unique=False)
    group_table = op.create_table('groups',
    sa.Column('type', sa.Enum('NONE', 'HUMAN', 'MYSTIC', 'MUTANT', name='grouptype'), nullable=False),
    sa.Column('enemies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Enum('NONE', 'HUMAN', 'MYSTIC', 'MUTANT', name='grouptype'), nullable=True),
    sa.Column('is_participant', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.type'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=True)
    op.create_index(op.f('ix_heroes_password_hash'), 'heroes', ['password_hash'], unique=False)
    # ### end Alembic commands ###

    # Seed data

    op.bulk_insert(
        group_table,
        [
            {'type': GroupType.HUMAN.name},
            {'type': GroupType.MYSTIC.name},
            {'type': GroupType.MUTANT.name},
            {'type': GroupType.NONE.name}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_password_hash'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_table('groups')
    op.drop_index(op.f('ix_fights_winner_name'), table_name='fights')
    op.drop_index(op.f('ix_fights_killed'), table_name='fights')
    op.drop_index(op.f('ix_fights_beaten_name'), table_name='fights')
    op.drop_table('fights')
    # ### end Alembic commands ###
